In [1]:
import numpy

In [3]:
array1=numpy.array([2,3,5,7,11,13,17,19])

In [4]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(8,)

In [8]:
array2=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [9]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
array2[2]
type(array2)

numpy.ndarray

In [11]:
array2.shape

(3, 4)

In [12]:
array1.size

8

In [13]:
array2.size

12

In [14]:
import numpy

In [15]:
array1=numpy.full(6,0)
array2=numpy.random.random(6)

In [16]:
array1

array([0, 0, 0, 0, 0, 0])

In [17]:
array2

array([0.03215102, 0.5660376 , 0.58401832, 0.56276514, 0.88134854,
       0.36838154])

In [18]:
type(array1)

numpy.ndarray

In [19]:
type(array2)

numpy.ndarray

In [20]:
array2.shape

(6,)

In [21]:
array1.size

6

In [22]:
import numpy as np

array1=np.full(6,0)
array2=np.random.random(6)

In [23]:
array1

array([0, 0, 0, 0, 0, 0])

In [24]:
array2

array([0.45787222, 0.35448004, 0.83288226, 0.84486709, 0.31944445,
       0.2306131 ])

In [25]:
array1[0]

0

In [27]:
array1[[1,3,4]]

array([0, 0, 0])

In [46]:
array2=np.array([2,1,3])

In [29]:
array1[array2]

array([0, 0, 0])

In [30]:
array1

array([0, 0, 0, 0, 0, 0])

In [31]:
array1[2:7]

array([0, 0, 0, 0])

In [32]:
import numpy as np

In [35]:
array1=np.arange(10)
array2=np.arange(10,20)

In [36]:
array1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
array1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [40]:
array1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
array1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [43]:
array1=array1+2

In [44]:
array1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])