In [2]:
import numpy as np
array1=np.arange(10)
array2=np.arange(10,20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [7]:
array1/array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])