In [4]:
import numpy as np
array1=np.array([[1,2,-1],[1,1,-3]])
array2=np.array([[3,2,-2],[-1,2,1]])

In [19]:
Q1=array1+array2
print(np.sum(array1,array2)

SyntaxError: unexpected EOF while parsing (<ipython-input-19-1af661e70fe5>, line 2)

In [11]:
array3=np.array([[3],[1],[2]])

In [12]:
array3

array([[3],
       [1],
       [2]])

In [17]:
print(np.dot(array1,array3))

[[ 3]
 [-2]]


In [9]:
array4=np.array([[3,2],[1,1],[2,-1]])

In [13]:
array4

array([[ 3,  2],
       [ 1,  1],
       [ 2, -1]])

In [18]:
print(np.dot(array1,array4))

[[ 3  5]
 [-2  6]]
