In [1]:
import numpy as np

b=np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [3]:
#3중 리스트
import numpy as np

c=np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [4]:
import numpy as np
d=np.zeros(8)
print(d)

e=np.ones(8)
print(e)

f=np.arange(8)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [5]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(np.shape(a))

(2, 3)


In [6]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a)
print()
print(a+3)
print()
print(a*3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [7]:
b=np.array([[0,1,2],[3,4,5]])
c=np.array([[2,0,1],
           [5,3,4]])
print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [8]:
b=np.array([[0,1,2],[3,4,5]])
print(b[1,2])

5


In [9]:
b[1,2]=9


print(b)

[[0 1 2]
 [3 4 9]]


In [10]:
c=np.array([[0,1,2],[3,4,5]])

print(c[1, :])

c[:,1]=np.array([6,7])
print(c)

[3 4 5]
[[0 6 2]
 [3 7 5]]


In [11]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print("합계:", np.sum(a))
print("평균:", np.average(a))
print("최댓값:",np.max(a))
print("최솟값:",np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


In [13]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
b=np.array([[5,4,3],[2,1,0]])

print("합계:",np.sum(a))
print("평균:",np.average(a))

합계: 15
평균: 2.5
합계:


(None, 30)

In [17]:
import numpy as np
a=np.array([[0,1,2],[1,2,3]])
b=np.array([[2,1],[2,1],[2,1]])
print(np.dot(a,b))

[[ 6  3]
 [12  6]]


In [21]:
import numpy as np
c=np.array([[0,1,2],[3,4,5],[6,7,8]])
d=np.array([[0,2,0],[2,0,2],[0,2,0]])
print(np.dot(c,d))

[[ 2  4  2]
 [ 8 16  8]
 [14 28 14]]
